export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const LOADING_PRODUCT =  "LOADING_PRODUCT";
export const GET_PRODUCT =  "GET_PRODUCT";
export const INSERT_PRODUCT =  "INSERT_PRODUCT";
export const UPDATE_PRODUCT =  "UPDATE_PRODUCT";
export const DELETE_PRODUCT =  "DELETE_PRODUCT";
export const ERROR_PRODUCT =  "ERROR_PRODUCT";