export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const LOADING_PRODUCT =  "LOADING_PRODUCT";

export const GET_PRODUCT =  "GET_PRODUCT";
export const RETRIEVED_PRODUCT = "RETRIEVED_PRODUCT";

export const INSERT_PRODUCT =  "INSERT_PRODUCT";
export const INSERTED_PRODUCT = "INSERTED_PRODUCT"

export const UPDATE_PRODUCT =  "UPDATE_PRODUCT";

export const DELETE_PRODUCT =  "DELETE_PRODUCT";
export const DELETED_PRODUCT = "DELETED_PRODUCT";

export const ERROR_PRODUCT =  "ERROR_PRODUCT";

export const GET_CART_PRODUCT = "GET_CART_PRODUCT";

export const LOADING_CART = "LOADING_CART";
export const GET_CART = "GET_CART";
export const INSERT_CART = "INSERT_CART";
export const UPDATE_CART =  "UPDATE_CART";
export const DELETE_CART =  "DELETE_CART";
export const ERROR_CART =  "ERROR_CART";