import {images} from '../assets/images';

export default ItemData = [
  {
    value: 1,
    Image: images.IMG_Iphone8_Png,
    title: '₹ 14,000',
    Text: 'Iphone 8 plus 64gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 2,
    Image: images.IMG_IphoneXR_Png,
    title: '₹ 18,000',
    Text: 'Iphone XR 128gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 3,
    Image: images.IMG_IphoneXS_Png,
    title: '₹ 26,500',
    Text: 'Iphone XS 256gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 4,
    Image: images.IMG_Iphone11_Png,
    title: '₹ 34,500',
    Text: 'Iphone 11 128gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 5,
    Image: images.IMG_Iphone111_Png,
    title: '₹ 36,500',
    Text: 'Iphone 11 256gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 6,
    Image: images.IMG_Iphone11PRO_Png,
    title: '₹ 40,999',
    Text: 'Iphone 11 Pro 128gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 7,
    Image: images.IMG_Iphone11MAX_Png,
    title: '₹ 55,999',
    Text: 'Iphone11 pro max...',
    Add: 'Subhash Nagar',
  },
  {
    value: 8,
    Image: images.IMG_Iphone13_Png,
    title: '₹ 64,000',
    Text: 'Iphone X 256gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 9,
    Image: images.IMG_Iphone13MAX_Png,
    title: '₹ 94,999',
    Text: 'Iphone 13 Pro Max 256gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 10,
    Image: images.IMG_Iphone13PRO_Png,
    title: '₹ 84,999',
    Text: 'Iphone 13 Pro 256gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 11,
    Image: images.IMG_IphoneX_Png,
    title: '₹ 20,000',
    Text: 'Iphone X 64gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 12,
    Image: images.IMG_Iphone12PRO_Png,
    title: '₹ 59,000',
    Text: 'Iphone 12 pro 256...',
    Add: 'Subhash Nagar',
  },
  {
    value: 13,
    Image: images.IMG_Iphone12_Png,
    title: '₹ 49,000',
    Text: 'Iphone 12 64gb',
    Add: 'Subhash Nagar',
  },
  {
    value: 14,
    Image: images.IMG_Iphone12MAX_Png,
    title: '₹ 70,000',
    Text: 'Iphone 12 pro max...',
    Add: 'Subhash Nagar',
  },
];

